# Workers will be run in the sequence given here
# Each worker has inputs and produces an output
# If the input is not known by the time the worker is run (from another, previous worker) then the user will be asked to enter it
#
# Note: user interaction is needed for tool use!
#
# worker: dictionary - key: string, value as below
#   inputs: list of strings
#   output: string
#   task: string
#   has_user_interaction: boolean, defaults to true
#   new_thread: boolean, defaults to true
#
#   assistant can be specified here with name and instruction or set up in the OpenAI platform and retrieved by assistant_id
#
#   name: string
#   instruction: string
#   functions: list of strings
#   model: GPT model, optional, defaults to gpt-4
#
# Note: It is advisable to create assistants via the platform dashboard because
#       all assistants created via the API will show and remain there until manually deleted!
#
# There has to be a worker that is called "Planner"
#
planner:
  assistant:
    name: DecisionMaker
    instruction: |
      You are a helpful assistant that decides on the best next action to take in a given situation. 
      You are handed a graph that describes various workers. Each worker takes some inputs and produces and output.
      Both inputs and outputs are documents. They are JSON format and they always contain a `markdown` field with human readable text in Markdown format.
      You can assume that the user is familiar with the contents of all documents; you do not need to show them. The `get_document` tool is for your convenience.
      The output of one worker becomes the input of the next worker.
      You have tools to ask for a list of all documents produced so far and you can also look at the details of a specific document.
      When a worker is used and one of its inputs is not yet avaialble, the worker will handle it and ask the user to enter it; but generally, aim to have all inputs available before the worker is used.
      NEVER ask the user to enter value for any document
      NEVER ask the user to enter value for any input
      Your job is to decide - collaboratively with the user - which worker should be used next. Once you decided, use your `choose_next_worker` tool.
    functions: 
    - get_document
    - list_all_procuded_documents
    - choose_next_worker
workers:
  Planner:
    inputs: 
      - "goal"
    output: "plan"
    task: "Plan"
    assistant:
      id: asst_2mHBz1buvQOIy5oK0wqCHHrh
      # to edit: https://platform.openai.com/assistants/asst_2mHBz1buvQOIy5oK0wqCHHrh
  Implementer:
    inputs: 
      - "goal"
      - "plan"
    output: "outcomes"
    task: "Implement"
    assistant:
      id: asst_VC7inEwBBi0mdz02HeJojGb1
      # to edit: https://platform.openai.com/assistants/asst_VC7inEwBBi0mdz02HeJojGb1
  Evaluator:
    inputs:
      - "goal"
      - "plan"
      - "outcomes"
    output: "feedback"
    task: "Evaluate"
    has_user_interaction: false
    assistant:
      id: asst_TbhTXb8yN4uEBUSMETQvn3Fa
      # to edit: https://platform.openai.com/assistants/asst_TbhTXb8yN4uEBUSMETQvn3Fa
  Fixer:
    inputs:
      - "goal"
      - "plan"
      - "outcomes"
      - "feedback"
    output: "reflection"
    task: "Fix and reflect"
    assistant:
      id: asst_DGaMd7sDXPMcXuRaA2f6K42X
      # to edit: https://platform.openai.com/assistants/asst_DGaMd7sDXPMcXuRaA2f6K42X
      functions:
        - web_search_qa
