# Workers will be run in the sequence given here
# Each worker has an input and produces and output
# If the input is not know by the time the worker is run (from another, previous worker) then the user will be asked to enter it
# assistant can be specified here with name and instruction or set up in the OpenAI platform and retrieved by assistant_id

"Worker One":
  input: "Subject"
  output: "Latest news"
  task: "Get some recent news"
  assistant:
    name: "News Getter"
    instruction: |
      You are a friendly assistant. You use your tools to get the latest news about the subject.
      Input: subject
      Output: recent news about the subject
    functions:
    - name: "web_search_qa"